modLoader = "javafml"
license = "${mod_license}"
issueTrackerURL = "https://github.com/Flatts3000/spawn-doctor/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/Flatts3000/spawn-doctor"
authors = "${mod_authors}"
logoFile = "logo.png"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
